### ISSUE TITLE
[ENHANCEMENT] Supporting Beam Search in EE-LLM

### ISSUE THREAD

**Issue by Marmot-C** [pan-x-c/EE-LLM#17]
Hi there, i've noticed that Megatron supports two types of generation paradigms in their framework, namely top-k/top-p based sampling methods (generate_and_post_process) and beam search (beam_search_and_post_proces). Currently EE-LLM only supports the generate_and_post_process branch. Do you have any plans on supporting beam search (s function in Megatron) in EE-LLM? Thanks.

**Comment by pan-x-c** [comment]
There are currently no plans.

Beam search involves batch inference, an unsolved challenge in EE model inference. Because different sequences in the same batch may trigger exit conditions at different layers, balancing the acceleration and output quality becomes a difficult problem.

**Comment by Marmot-C** [comment]
I see. Adding beam search could be really challenging indeed. Thanks a lot for the reply!
