### ISSUE TITLE
[QUESTION]Using HELM tool for EE-model in Megatron format

### ISSUE THREAD

**Issue by BenWu11** [pan-x-c/EE-LLM#8]
Hi!
 
 I'm attempting to utilize the HELM tool to benchmark the EE model as mentioned in the paper. 
 Hence, I initially believe I need to convert the ckpt format into the Hugging Face format and then utilize the HELM tool to test the EE model. However, this approach seems impractical. 
 
 Could you provide some methods for using the HELM tool with the EE model in Megatron-LM format?"
 Thanks.
 
 
![image](https://github.com/pan-x-c/EE-LLM/assets/142816339/57f0b8cf-bb2d-4bb2-93ec-fbcdea1c8830)

**Comment by pan-x-c** [comment]
HELM has a megatron-lm connector, you can try to modify this connector and add EE configurations
