### ISSUE TITLE
[QUESTION] The default setting regarding adding an early exit layer.

### ISSUE THREAD

**Issue by BenWu11** [pan-x-c/EE-LLM#9]
Hello!

If I just run the instruction `./examples/ee_tuning/convert/add_exit_layers.sh`  in default which is not appended any parameters.
So like the Fig.[1], we will add early-exit layer including `mlp,block,normalization at the same time`.
But `including mlp,block,normalization at the same time` 'doesn't conform to the following three scenarios in Figure 2

Fig.[1]
![image](https://github.com/pan-x-c/EE-LLM/assets/142816339/c13a64be-1c33-441b-ad57-4265cf033435)

Fig.[2]
![image](https://github.com/pan-x-c/EE-LLM/assets/142816339/20cf9c66-31d7-4f24-b96a-2bfbb116e878)

**Comment by yanxi-chen** [comment]
Hello! To clarify,
* Figure 2 (a) corresponds to `--use-exit-norm` 
* Figure 2 (b) corresponds to `--use-exit-norm  --use-exit-mlp`
* Figure 2 (c) corresponds to `--use-exit-norm  --use-exit-block`

Not appending any of these parameters will imply a minimalistic early exit that contains only an output embedding matrix, *without* any norm/mlp/block module. See e.g. the code block starting from Line 12 in `./examples/ee_tuning/convert/add_exit_layers.sh`. 

In addition, our codebase currently does not support using `--use-exit-mlp` and `--use-exit-block` at the same time.
